from typing import List, Optional

from knot_resolver.datamodel.types import IDPattern, Percent, ReadableFile
from knot_resolver.utils.modeling import ConfigSchema


class DGAFilterSchema(ConfigSchema):
    """
    Block suspected domains generated by DGA.

    ---
    enable: enable/disable this filtering
    file: path to the machine learning model to be used
    threshold: machine learning model inference threshold in percentage
    tags: set of tags when to apply the filtering (same as in other local-data)
    """

    enable: bool = False
    file: Optional[ReadableFile] = None
    threshold: Percent = Percent(31)
    tags: Optional[List[IDPattern]] = None

    def _validate(self) -> None:
        if not self.enable:
            return
        if self.file is None:
            raise ValueError("missing path to the machine learning model file")
