"""
This type stub file was generated by pyright.
"""

import sys
from typing import Any, Optional

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, ):
    url_quote = ...
else:
    ...
PY2: Any
PYPY: Any
unichr: Any
range_type: Any
text_type: Any
string_types: Any
integer_types: Any
iterkeys: Any
itervalues: Any
iteritems: Any
NativeStringIO: Any
def reraise(tp, value, tb: Optional[Any] = ...):
    ...

ifilter: Any
imap: Any
izip: Any
intern: Any
implements_iterator: Any
implements_to_string: Any
encode_filename: Any
get_next: Any
def with_metaclass(meta, *bases):
    ...
