stages:
  - check

variables:
  PYTHON_INTERPRETER: python3.12

default:
  image: $IMAGE_PREFIX/manager:$IMAGE_TAG
  before_script:
    - poetry --version
    - poetry env use $PYTHON_INTERPRETER
    - poetry install --all-extras
  tags:
    - docker
    - linux
    - amd64

examples:
  stage: check
  script:
    - poe examples

check:
  stage: check
  script:
    - poe check

format:
  stage: check
  script:
    - poe format

lint:
  stage: check
  script:
    - poe lint

.python_interpreters: &python_interpreters
  parallel:
    matrix:
      - PYTHON_INTERPRETER: [
        python3.8,
        python3.9,
        python3.10,
        python3.11,
        python3.12,
        python3.13,
      ]

test:
  stage: check
  <<: *python_interpreters
  script:
    - poe test
    # the following command makes sure that the source root of the coverage file is at $gitroot
    - poetry run bash -c "coverage combine .coverage; coverage xml"
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: unit.junit.xml
    paths:
      - unit.junit.xml
