info:
	$(info )
	$(info Target:     Knot DNS Resolver $(MAJOR).$(MINOR)-$(PLATFORM))
	$(info Compiler:   $(CC))
	$(info CFLAGS:     $(CFLAGS))
	$(info LDFLAGS:    $(LDFLAGS))
	$(info PREFIX:     $(PREFIX))
	$(info BINDIR:     $(BINDIR))
	$(info LIBDIR:     $(LIBDIR))
	$(info INCLUDEDIR: $(INCLUDEDIR))
	$(info )
	$(info Features)
	$(info --------)
	$(info [$(HAS_libknot)] library (libknot))
	$(info [$(HAS_libuv)] daemon (libuv))
	$(info [$(HAS_cmocka)] unit tests (libcmocka))
	$(info [$(HAS_python)] integration tests (libpython))
	$(info )