site_name: Knot Resolver
site_url: !ENV READTHEDOCS_CANONICAL_URL
theme:
  name: readthedocs
  navigation_depth: 1
  logo: logo-negativ.svg
nav:
  - "Documentation moved": index.md
extra_css:
  - user.css
plugins: []
