# -*- coding: utf-8 -*-

from setuptools import setup

package_dir = {
    "": "python"
}

packages = [
    "knot_resolver",
    "knot_resolver.client",
    "knot_resolver.client.commands",
    "knot_resolver.controller",
    "knot_resolver.controller.supervisord",
    "knot_resolver.controller.supervisord.plugin",
    "knot_resolver.datamodel",
    "knot_resolver.datamodel.templates",
    "knot_resolver.datamodel.types",
    "knot_resolver.manager",
    "knot_resolver.manager.files",
    "knot_resolver.manager.metrics",
    "knot_resolver.utils",
    "knot_resolver.utils.compat",
    "knot_resolver.utils.modeling"
]

package_data = {
    "knot_resolver": [
        "controller/supervisord/*.j2",
        "datamodel/templates/*.j2",
        "datamodel/templates/macros/*.j2"
    ]
}

install_requires = [
    "aiohttp",
    "jinja2",
    "pyyaml",
    "supervisor",
    "typing-extensions"
]

extras_require = {
    "prometheus": [
        "prometheus-client"
    ],
    "watchdog": [
        "watchdog"
    ]
}

entry_points = {
    "console_scripts": [
        "kresctl = knot_resolver.client.main:main",
        "knot-resolver = knot_resolver.manager.main:main"
    ]
}

setup_kwargs = {
    "name": "knot-resolver",
    "version": "6.4.2",
    "description": "Knot Resolver Manager - a Python program that automatically manages the other components of the resolver",
    "maintainer": "Knot Resolver team",
    "maintainer_email": "knot-resolver@labs.nic.cz",
    "url": "https://www.knot-resolver.cz",
    "package_dir": package_dir,
    "packages": packages,
    "package_data": package_data,
    "install_requires": install_requires,
    "extras_require": extras_require,
    "entry_points": entry_points,
    "python_requires": ">=3.9,<4.0",
}

setup(**setup_kwargs)

# This setup.py was autogenerated using create_setup.py script for backward compability with older setuptools.

