#!/bin/bash

# fail early
set -e

cd /test
echo "Starting manager..."
cmd=$(grep ExecStart /etc/systemd/system/knot-resolver-manager.service | sed 's/ExecStart=//')
bash -c "cd /code; $cmd" &

# give it time to start
while [ ! -e /tmp/manager.sock ]; do sleep 0.5; done

python3 send_request.py

# assert that any kresd process is running
ps aux | grep -v grep | grep kresd
