#!/bin/bash

# fail early
set -e

cd /test
echo "Starting manager..."
systemctl start knot-resolver-manager.service

# give it time to start
sleep 1

python3 send_request.py

# assert that any kresd process is running
systemctl status | grep kresd

# see the rendered Lua configuration
echo "Lua config in '/etc/knot-resolver/kresd.conf':"
cat /etc/knot-resolver/kresd.conf
