#!/bin/bash

script_dir="$(dirname "$(realpath "$BASH_SOURCE[0]")")"

if poetry run python -c 'import sys; sys.exit(0 if sys.version_info >= (3, 8) else 1)'; then
    poetry --directory "$script_dir" run poe --root "$script_dir" $@
else
    echo "Unsupported Python version - must be >=3.8" >&2
    exit 1
fi
