# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure(2) do |config|

    config.vm.box = "centos/7"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define "centos7_knot-resolver"  do |machine|
        machine.vm.provision "ansible" do |ansible|
            ansible.playbook = "../knot-resolver-test.yaml"
        end
    end

end
