# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure(2) do |config|

    config.vm.box = "openSUSE-Leap-15.1-Vagrant.x86_64"
    config.vm.box_url = "https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/openSUSE-Leap-15.1/images/boxes/openSUSE-Leap-15.1-Vagrant.x86_64.json"

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define "leap15_knot-resolver"  do |machine|
        machine.vm.provision "ansible" do |ansible|
            ansible.playbook = "../knot-resolver-pkgtest.yaml"
        end
    end

    config.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 1
      libvirt.memory = 1024
    end

    config.vm.provider :virtualbox do |vbox|
      vbox.cpus = 1
      vbox.memory = 1024
    end

end
