#!/bin/bash

# fail early
set -e

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/_env.sh


# build the actual containers
for tag in $(find containers -maxdepth 1 -type d -printf '%f\n' | grep -v containers); do
    podman build -t "knot-manager:$tag" -f "containers/$tag/Containerfile" .
done