#!/bin/bash

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/_env.sh

aggregate_rv=0
function check_rv {
	if test "$1" -eq 0; then
		echo -e "  ${green}OK${reset}"
	fi
	aggregate_rv=$(( $aggregate_rv + $1 ))
}


# stop failing early, because we wouldn't do anything else than fail
set +e

# check formatting using black
echo -e "${yellow}Checking formatting using black...${reset}"
black knot_resolver_manager tests scripts --check --diff
check_rv $?
echo

# check code with pylint
echo -e "${yellow}Linting using pylint...${reset}"
pylint knot_resolver_manager
check_rv $?
echo

# check code with flake8
echo -e "${yellow}Linting using flake8...${reset}"
flake8 knot_resolver_manager
check_rv $?
echo

# check types with pyright
echo -e "${yellow}Type checking using pyright...${reset}"
pyright knot_resolver_manager
check_rv $?
echo


# check that setup.py is not behind pyproject.toml
echo -e "${yellow}Checking setup.py${reset}"
python scripts/create_setup.py | diff - setup.py
check_rv $?
python setup.py --help > /dev/null
check_rv $?
echo

# fancy messages at the end :)
if test "$aggregate_rv" -eq "0"; then
	echo -e "${green}Everything looks great!${reset} 🥳🎉🥰"
else
	echo -e "${red}Failure.${reset}"
	echo -e "${red}These commands might help you:${reset}"
	echo -e "${red}\tpoe format${reset}"
	echo -e "${red}\tpoe gen-setuppy${reset}"
	echo -e "${red}That's not great. Could you please fix that?${reset} 😲😟"
fi

# exit with the aggregate return value
exit $aggregate_rv
