#!/bin/bash

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/_env.sh


# run code check
poe check

# run unit tests
poe test

# run integration tests
poe integration

# invoke commit
git commit $@