#!/bin/bash

# fail early
set -e

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/_env.sh


if test "$#" -eq 0; then
    containers="$(find containers -maxdepth 1 -type d -printf '%f\n' | grep -v containers)"
else
    containers="$@"
fi


# build all configured containers
for tag in $containers; do
    podman build -t "knot-manager:$tag" -f "containers/$tag/Containerfile" .
done