#!/bin/bash

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/_env.sh
cd ..

echo Building documentation for Knot Resolver
meson build_doc -Ddoc=enabled

# install "knot_resolver" python module
pip install -e build_doc/python

# build documentation
ninja -C build_doc doc
