#!/bin/bash

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/_env.sh

pushd ..
reconfigure=''
if [ -f manager/.build_kresd/ninja.build ]; then
	reconfigure='--reconfigure'
fi
meson setup manager/.build_kresd "$reconfigure" --prefix=$(realpath manager/.install_kresd) "$@"
popd

build_kresd
