#!/bin/bash

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/_env.sh


# Debian 10 packaging
if [[ -f "/etc/debian_version" && "$(cat /etc/debian_version)" == 10.* ]] ; then
    # if running on debian 10, just run the packaging process

    # if possible, make sure we use the latest apkg
    if [[ "$(id -u)" == "0" ]]; then
        python3 -m pip install -U apkg
        apt update
    fi
    
    apkg build -i
elif [[ "${container:-}" != "podman" ]]; then
    # if not running debian 10 and not running inside a container, launch a build container and try again
    poe container run -c --artifact /code/pkg/pkgs/debian-10:pkg/pkgs/debian-10 --artifact /code/pkg/srcpkgs/debian-10:pkg/srcpkgs/debian-10 -- debian10 scripts/package
else
    echo -e "${red}Debian 10 package creation skipped...${reset}"
fi