#!/bin/bash

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/_env.sh

echo
echo Building Knot Resolver
echo ----------------------
echo -e "${blue}In case of an compilation error, run this command to try to fix it:${reset}"
echo -e "\t${blue}rm -r $(realpath .install_kresd) $(realpath .build_kresd)${reset}"
echo
cd ..
mkdir -p manager/.build_kresd manager/.install_kresd
meson manager/.build_kresd --prefix=$(realpath manager/.install_kresd) --default-library=static --buildtype=debug
ninja -C manager/.build_kresd
ninja install -C manager/.build_kresd
export PATH="$(realpath manager/.install_kresd)/sbin:$PATH"
cd manager

echo
echo Building Knot Resolver Manager native extensions
echo ------------------------------------------------
poetry build
# copy native modules from build directory to source directory
shopt -s globstar
shopt -s nullglob
for d in build/lib*; do
    for f in "$d/"**/*.so; do
        cp -v "$f" ${f#"$d/"}
    done
done
shopt -u globstar
shopt -u nullglob


echo
echo Knot Manager API is accessible on http://localhost:5000
echo -------------------------------------------------------

poetry run python -m knot_resolver_manager -c etc/knot-resolver/config.dev.yml $@
