network:
    interfaces:
      - listen: 127.0.0.1
      - listen: 127.0.0.1
        kind: dot
      - listen: ::1
        freebind: true
      - listen: ::1
        kind: dot
        freebind: true
    edns_buffer_size:
        downstream: 4K
options:
    prediction: true
cache:
    size_max: 100M
