cache:
  storage: /var/cache/knot-resolver
logging:
  level: info
network:
  interfaces:
    - listen:
        ip: 127.0.0.1
        port: 53
server:
  workers: 1
  management:
    listen:
      unix-socket: /run/knot-resolver/manager.sock
    log-level: DEBUG
    rundir: /run/knot-resolver
