cache:
  storage: /var/cache/knot-resolver
logging:
  level: info
network:
  listen:
    - interface: 127.0.0.1@53
server:
  id: distro
  workers: 2
  rundir: /run/knot-resolver
  management:
    unix-socket: /run/knot-resolver/manager.sock
