rundir: etc/knot-resolver/runtime
workers: 1
management:
  interface: 127.0.0.1@5000
cache:
  storage: ../cache
logging:
  level: notice
  groups:
    - manager
    - supervisord
network:
  listen:
    - interface: [127.0.0.1@5353]

views:
  - subnets: [127.0.0.0/24]
    tags: [t01, t02, t03]
    options:
      dns64: false
  - subnets: [ 0.0.0.0/0, "::/0" ]
    answer: refused
  - subnets: [10.0.10.0/24]
    answer: allow

local-data:
  subtrees:
    - type: empty
      tags: [ t2 ]
      roots: [ example1.org ]
    - type: nxdomain
      roots: [ sub4.example.org ]

#   ttl: 1d
#   nodata: true
#   addresses:
#     foo.bar: [ 127.0.0.1, "::1" ]
#     my.pc.corp: 192.168.12.95
#   addresses-files:
#     - /etc/hosts
#   records: |
#     example.net. TXT "foo bar"
#      A 192.168.2.3
#      A 192.168.2.4
#     local.example.org AAAA ::1

# forward:
#   - subtree: '.'
#     servers:
#       - address: [ 192.0.2.1, 192.0.2.2@5353 ]
#         transport: tls
#         pin-sha256: Wg==
#       - address: 2001:DB8::d0c
#         transport: tls
#         hostname: res.example.com
#         ca-file: /etc/knot-resolver/tlsca.crt
#     options:
#       dnssec: true  # default
#   - subtree: 1.168.192.in-addr.arpa
#     servers: [ 192.0.2.1@5353 ]
#     options:
#       dnssec: false # policy.STUB?