# Refer to manual: https://knot-resolver.readthedocs.io/en/stable/

network:
  listen:
    # unencrypted DNS on port 53
    - interface: &interfaces
        - 127.0.0.1
        - "::1"
    # DNS over TLS on port 853
    - interface: *interfaces
      kind: dot
    # DNS over HTTPS on port 443
    - interface: *interfaces
      kind: doh2

forward:
  # define list of internal-only domains
  - subtree:
      - company.example
      - internal.example
    # forward all queries belonging to domains in the list above to IP address '192.0.2.44'
    servers:
      - 192.0.2.44
    # common options configuration for internal-only domains
    options:
      authoritative: true
      dnssec: false
