cache:
  storage: /var/cache/knot-resolver
logging:
  level: debug
network:
  interfaces:
    - listen:
        ip: 127.0.0.1
        port: 5353
server:
  workers: 1
  management:
    listen:
      ip: 127.0.0.1
      port: 5000
    log-level: DEBUG
    rundir: /run/knot-resolver
