# SPDX-License-Identifier: GPL-3.0-or-later
# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure(2) do |config|

    config.vm.box = "fedora/35-cloud-base"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define "fedora35_knot-resolver"  do |machine|
        machine.vm.provision "ansible" do |ansible|
            ansible.playbook = "../knot-resolver-pkgtest.yaml"
            ansible.extra_vars = {
                ansible_python_interpreter: "/usr/bin/python3",
            }
        end
    end

    config.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 1
      libvirt.memory = 1024
    end

    config.vm.provider :virtualbox do |vbox|
      vbox.cpus = 1
      vbox.memory = 1024
    end

end
