#!/usr/bin/env bash

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/utils/_env.sh

meson_setup_configure -Ddoc=enabled

echo ----------------------------------
echo Building documentation using ninja
echo ----------------------------------
ninja -C $build_dir doc
echo
