#!/usr/bin/env bash

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/utils/_env.sh

echo Building Knot Resolver documentation
echo ------------------------------------
meson build_doc -Ddoc=enabled
ninja -C build_doc doc
