#!/usr/bin/env bash

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/utils/_env.sh

# validate all configuration examples
for example in $PWD/etc/config/config.example.*.yaml;
do
    poe kresctl validate --no-strict $example;
done
