#!/usr/bin/env bash

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/utils/_env.sh

dirs="python/knot_resolver/ tests/manager scripts/poe-tasks/utils/create_setup.py"

# sort python import
ruff check --select I --fix $dirs

# format python code
ruff format $dirs
