#!/usr/bin/env bash

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/_env.sh

dirs="python/knot_resolver/ tests/manager scripts/create_setup.py build_c_extensions.py"

# run black code formater
black $dirs

# sort python imports
isort $dirs
