#!/usr/bin/env bash

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/utils/_env.sh

echo
is_build_dev_dir_configured
echo

# run knot-resolver client
python3 -m knot_resolver.client --config "$KRES_DEV_CONFIG_FILE" "$@"
