#!/usr/bin/env bash

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/utils/_env.sh

is_buil_dir_configured

# run knot-resolver client
python3 -m knot_resolver.client --config "$KRES_CONFIG_FILE" "$@"
