#!/usr/bin/env bash

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/utils/_env.sh

ninja_install

echo
echo ---------------------------------------
echo Building Python komponents using Poetry
echo ---------------------------------------
poetry build
# copy native modules from build directory to source directory
shopt -s globstar
shopt -s nullglob
for d in build/lib*; do
    for f in "python/$d/"**/*.so; do
        cp -v "$f" ${f#"python/$d/"}
    done
done
shopt -u globstar
shopt -u nullglob

echo
echo --------------------------------------
echo Starting Knot Resolver wit the Manager
echo --------------------------------------
python3 -m knot_resolver.manager --config "$KRES_CONFIG_FILE" "$@"
