#!/bin/bash

# ensure consistent behaviour
src_dir="$(dirname "$(realpath "$0")")"
source $src_dir/_env.sh

echo The debug server will be listening on port localhost:5678
echo Use VSCode remote attach feature to connect to the debug server
echo The manager will start after you connect
echo API will be running on port 5000
echo ----------------------------------------

KRES_DEBUG_MANAGER=1 poe run $@