# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure(2) do |config|

    config.vm.box = "generic/ubuntu1804"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define "ubuntu1804_knot-resolver"  do |machine|
        machine.vm.provision "ansible" do |ansible|
            ansible.playbook = "../knot-resolver-test.yaml"
            ansible.extra_vars = {
                ansible_python_interpreter: "/usr/bin/python3"
            }
        end
    end

end
