#!/bin/bash

# fail early
set -e

cd /test
echo "Starting manager..."
systemctl start knot-resolver-manager.service

# give it time to start
while [ ! -e /tmp/manager.sock ]; do sleep 0.5; done

python3 run_test.py
