FROM knot-manager:debian

# Remove systemd
# RUN apt-get remove -y systemd
#
# Well, we can't do that... The command above also uninstalls knot-resolver. Which
# is kind of stupid. So let's just keep systemd installed and not start it.

# install supervisord
RUN python3 -m pip install supervisor

# install tini init
RUN apt-get update \
  && apt-get install --no-install-recommends -y tini \
  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
  && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# replace systemd with dummy init
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/bin/sleep", "inf"]