#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import subprocess

from pathlib import Path
from pprint import pformat
from setuptools import find_packages
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib

GIT_ROOT = Path(
    subprocess.check_output(
        ["git", "rev-parse", "--show-toplevel"],
        text=True,
    ).strip()
)

with (GIT_ROOT / "pyproject.toml").open("rb") as pyproject_file:
    pyproject: dict[str, Any] = tomllib.load(pyproject_file)

project = pyproject["project"]
tool_setuptools = pyproject.get("tool", {}).get("setuptools", {})

packages_find = tool_setuptools.get("packages", {}).get("find", {})
where = packages_find.get("where", ["."])
if isinstance(where, list):
    where = where[0]
scripts = project.get("scripts", {})

# prepare setup entries
package_dir = tool_setuptools.get("package-dir", {"": "."})
packages = find_packages(where=where)
packages.sort()
package_data = tool_setuptools.get("package-data", {})
install_requires = project.get("dependencies", [])
extras_require = project.get("optional-dependencies", {})
entry_points = {
    "console_scripts": [
        f"{name} = {target}"
        for name, target in scripts.items()
    ]
}

# read version from the VERSION file
with (GIT_ROOT / "VERSION").open() as version_file:
    version: str = version_file.read().strip()

# setup.py template
setup_py = f"""# -*- coding: utf-8 -*-

from setuptools import setup


package_dir = \\
{pformat(package_dir)}

packages = \\
{pformat(packages)}

package_data = \\
{pformat(package_data)}

install_requires = \\
{pformat(install_requires)}

extras_require = \\
{pformat(extras_require)}

entry_points = \\
{pformat(entry_points)}

setup_kwargs = {{
    'name': '{project["name"]}',
    'version': '{version}',
    'description': '{project["description"]}',
    'maintainer': '{project["maintainers"][0]["name"]}',
    'maintainer_email': '{project["maintainers"][0]["email"]}',
    'url': '{project["urls"]["homepage"]}',
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'extras_require': extras_require,
    'entry_points': entry_points,
    'python_requires': '{project["requires-python"]}',
}}

setup(**setup_kwargs)

# This setup.py was autogenerated using create_setup.py script for backward compability with older setuptools.
"""

print(setup_py)
