debian/init-d-script usr/lib/knot-resolver/
debian/kresd.conf etc/knot-resolver/
etc/knot-resolver/config.* /usr/share/doc/knot-resolver/examples/
distro/common/systemd/kresd-control@.socket lib/systemd/system/
distro/common/systemd/kresd-tls.socket lib/systemd/system/
distro/common/systemd/kresd.socket lib/systemd/system/
distro/common/systemd/kresd@.service lib/systemd/system/
distro/common/systemd/kresd.target lib/systemd/system/
distro/common/tmpfiles/knot-resolver.conf usr/lib/tmpfiles.d/
usr/lib/knot-resolver/*.so
usr/lib/knot-resolver/daf.lua
usr/lib/knot-resolver/daf/
usr/lib/knot-resolver/detect_time_jump.lua
usr/lib/knot-resolver/detect_time_skew.lua
usr/lib/knot-resolver/dns64.lua
usr/lib/knot-resolver/etcd.lua
usr/lib/knot-resolver/experimental_dot_auth.lua
usr/lib/knot-resolver/graphite.lua
usr/lib/knot-resolver/http_trace.lua
usr/lib/knot-resolver/kres-gen.lua
usr/lib/knot-resolver/kres.lua
usr/lib/knot-resolver/policy.lua
usr/lib/knot-resolver/predict.lua
usr/lib/knot-resolver/prefill.lua
usr/lib/knot-resolver/priming.lua
usr/lib/knot-resolver/prometheus.lua
usr/lib/knot-resolver/rebinding.lua
usr/lib/knot-resolver/renumber.lua
usr/lib/knot-resolver/serve_stale.lua
usr/lib/knot-resolver/ta_sentinel.lua
usr/lib/knot-resolver/ta_signal_query.lua
usr/lib/knot-resolver/trust_anchors.lua
usr/lib/knot-resolver/view.lua
usr/lib/knot-resolver/workarounds.lua
usr/lib/knot-resolver/zonefile.lua
usr/sbin/kresc
usr/sbin/kresd
