"""
This type stub file was generated by pyright.
"""

RCS_ID = ...
get_header = ...
class auth_handler:
    def __init__(self, dict, handler, realm=...) -> None:
        ...
    
    def match(self, request):
        ...
    
    def handle_request(self, request): # -> None:
        ...
    
    def handle_unauthorized(self, request): # -> None:
        ...
    
    def make_nonce(self, request): # -> bytes:
        """A digest-authentication <nonce>, constructed as suggested in RFC 2069"""
        ...
    
    def apply_hash(self, s): # -> bytes:
        """Apply MD5 to a string <s>, then wrap it in base64 encoding."""
        ...
    
    def status(self): # -> composite_producer:
        ...
    


class dictionary_authorizer:
    def __init__(self, dict) -> None:
        ...
    
    def authorize(self, auth_info): # -> Literal[1, 0]:
        ...
    


AUTHORIZATION = ...
