"""
This type stub file was generated by pyright.
"""

class counter:
    """general-purpose counter"""
    def __init__(self, initial_value=...) -> None:
        ...
    
    def increment(self, delta=...): # -> Unknown:
        ...
    
    def decrement(self, delta=...): # -> Unknown:
        ...
    
    def as_long(self): # -> int:
        ...
    
    def __nonzero__(self):
        ...
    
    __bool__ = ...
    def __repr__(self): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
