"""
This type stub file was generated by pyright.
"""

def html_repr(object): # -> str:
    ...

def progressive_divide(n, parts): # -> list[Unknown]:
    ...

def split_by_units(n, units, dividers, format_string): # -> list[Unknown]:
    ...

def english_bytes(n): # -> list[str]:
    ...

def english_time(n): # -> list[str]:
    ...
