"""
This type stub file was generated by pyright.
"""

VERSION = ...
class xmlrpc_handler:
    def match(self, request): # -> Literal[1, 0]:
        ...
    
    def handle_request(self, request): # -> None:
        ...
    
    def continue_request(self, data, request): # -> None:
        ...
    
    def call(self, method, params): # -> NoReturn:
        ...
    


class collector:
    """gathers input for POST and PUT requests"""
    def __init__(self, handler, request) -> None:
        ...
    
    def collect_incoming_data(self, data): # -> None:
        ...
    
    def found_terminator(self): # -> None:
        ...
    


if __name__ == '__main__':
    class rpc_demo(xmlrpc_handler):
        def call(self, method, params): # -> Literal['Sure, that works']:
            ...
        
    
    
    hs = ...
    rpc = ...
