# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure(2) do |config|

    config.vm.box = "debian/stretch64"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define "debian9"  do |debian9|
        debian9.vm.provision "ansible" do |ansible|
            ansible.playbook = "../knot-resolver-test.yaml"
        end
    end

end
