# Refer to manual: https://www.knot-resolver.cz/documentation/latest/

network:
  listen:
    # unencrypted DNS on port 53
    - interface: &interfaces
        - 127.0.0.1
        - "::1"
    # DNS over TLS on port 853
    - interface: *interfaces
      kind: dot
    # DNS over HTTPS on port 443
    # - interface: *interfaces
    #   kind: doh2

cache:
  size-max: 100M
  # prefetch expiring/frequent records
  prefetch:
    expiring: true
    prediction:
      period: 24
      window: 15m
