workers: 1
management:
  interface: 127.0.0.1@5000
logging:
  level: notice
  groups:
    - manager
    - supervisord
network:
  listen:
    - interface: 127.0.0.1@5353
views:
  - subnets: [127.0.0.0/24]
    tags: [t01, t02, t03]
    options:
      dns64: false
  - subnets: [0.0.0.0/0, "::/0"]
    answer: refused
  - subnets: [10.0.10.0/24]
    answer: allow
local-data:
  ttl: 60m
  nodata: false
  addresses:
    foo.bar: 127.0.0.1
  addresses-files:
    - /etc/hosts
  records: |
    example.net. TXT "foo bar"
     A 192.168.2.3
     A 192.168.2.4
    local.example.org AAAA ::1
  rules:
    - name: custom.example
      address: 1.2.3.4
      nodata: true
      tags: [t01]
    - subtree: empty
      tags: [ t02 ]
      name: [ example1.org ]
    - subtree: nxdomain
      name: [ sub4.example.org ]
  #   - file: hosts.custom
  #     tags: [t02]
  #     ttl: 10m
  # rpz:
  #   - file: runtime/blocklist.rpz
  #     tags: [t01, t02]
forward:
  - subtree: '.'
    options:
      dnssec: true
      authoritative: false
    servers:
      - address: [2001:148f:fffe::1, 185.43.135.1]
        transport: tls
        hostname: odvr.nic.cz
      - address: [ 192.0.2.1, 192.0.2.2 ]
        transport: tls
        pin-sha256:
          - d6qzRu9zOECb90Uez27xWltNsj0e1Md7GkYYkVoZWmM=
          - E9CZ9INDbd+2eRQozYqqbQ2yXLVKB9+xcprMF+44U1g=
  - subtree: 1.168.192.in-addr.arpa
    options:
      dnssec: false
    servers: [ 192.0.2.1@5353 ]
