"""
This type stub file was generated by pyright.
"""

def getRPCTransport(env): # -> SupervisorTransport:
    ...

def getRPCInterface(env):
    ...

def get_headers(line): # -> dict[Unknown, Unknown]:
    ...

def eventdata(payload): # -> tuple[dict[Unknown, Unknown], Unknown]:
    ...

def get_asctime(now=...): # -> str:
    ...

class ProcessCommunicationsProtocol:
    def send(self, msg, fp=...): # -> None:
        ...
    
    def stdout(self, msg): # -> None:
        ...
    
    def stderr(self, msg): # -> None:
        ...
    


pcomm = ...
class EventListenerProtocol:
    def wait(self, stdin=..., stdout=...): # -> tuple[dict[Unknown, Unknown], Unknown]:
        ...
    
    def ready(self, stdout=...): # -> None:
        ...
    
    def ok(self, stdout=...): # -> None:
        ...
    
    def fail(self, stdout=...): # -> None:
        ...
    
    def send(self, data, stdout=...): # -> None:
        ...
    


listener = ...
