"""
This type stub file was generated by pyright.
"""

""" An executable which proxies for a subprocess; upon a signal, it sends that
signal to the process identified by a pidfile. """
class PidProxy:
    pid = ...
    def __init__(self, args) -> None:
        ...
    
    def go(self): # -> None:
        ...
    
    def usage(self): # -> None:
        ...
    
    def setsignals(self): # -> None:
        ...
    
    def reap(self, sig, frame): # -> None:
        ...
    
    def passtochild(self, sig, frame): # -> None:
        ...
    


def main(): # -> None:
    ...

if __name__ == '__main__':
    ...
